AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - '{bin,config,db,log,vendor,tmp}/**/*'
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 80

Style/AccessorGrouping:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false
