language: ruby
rvm: 2.7.0
before_install:
- gem update --system
- gem install bundler
before_script: bin/rails db:create
cache: bundler
script:
- bin/rails test
- bundle exec rubocop --parallel
- bundle exec brakeman -z
- bundle exec srb tc
services:
- postgresql
