name: Main
on:
- push
- pull_request_target
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: true
      DATABASE_URL: postgres://postgres:@localhost:5432/test
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:11.5
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - run: sudo apt-get -yqq install libpq-dev
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true
    - name: Setup database
      run: bin/rails db:setup
    - name: Lint and test
      run: |
        bundle exec rubocop --parallel
        bundle exec brakeman -z
        bundle exec rake test
  automerge:
    name: AutoMerge
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && (github.actor == github.repository_owner || github.actor == 'dependabot[bot]')
    steps:
    - uses: actions/github-script@v3
      with:
        script: |
          github.pulls.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number
          })
